-- Create User Table
CREATE TABLE IF NOT EXISTS users (
  userId SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  userName VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  googleId VARCHAR(255),
  userIdOnBlockchain VARCHAR(255) NOT NULL,
  files VARCHAR(255) NOT NULL,
  referenceLocation VARCHAR(255) NOT NULL,
  dataSharable BOOLEAN NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create File Table
CREATE TABLE IF NOT EXISTS files (
  fileId SERIAL PRIMARY KEY,
  userId INT REFERENCES users(userId) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  expirationTime INT NOT NULL,
  url VARCHAR(255) NOT NULL,
  fileuuid VARCHAR(255) NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Symptom Table
CREATE TABLE IF NOT EXISTS symptoms (
  symptomId SERIAL PRIMARY KEY,
  description TEXT NOT NULL,
  result TEXT NOT NULL,
  confidenceRateOfResult INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
